pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.aliyun.com/repository/public" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.aliyun.com/repository/public" }
    }
}

rootProject.name = "NewBlackbox"

include ':app'
include ':blackbox-gallery-stub'
include(":black-reflection")
include(":compiler")
include ':Bcore'
